export interface CompaniesQuery {
    nip?: string,
    regon?: string,
    companyName?: string,
    PKDCode?: string,
    status?: string,
    businessOwnerFirstName?: string,
    businessOwnerLastName?: string,
    street?: string,
    houseNumber?: string,
    apartmentNumber?: string,
    city?: string,
    postcode?: string,
    voivodeship?: string,
    district?: string,
    community?: string,
    startDateFrom?: string,
    startDateTo?: string, 
    updateDateFrom?: string,
    updateDateTo?: string,
}
  